import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: [
    './app/**/*.{vue,js,ts}',
    './components/**/*.{vue,js,ts}',
    './layouts/**/*.{vue,js,ts}',
    './composables/**/*.{vue,js,ts}',
    './stores/**/*.{vue,js,ts}',
    './tests/**/*.{vue,js,ts}',
  ],
  theme: {
    extend: {
      colors: {
        'outline-variant': 'var(--color-outline-variant)',
        'error-dim': 'var(--color-error-dim)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'error-container': 'var(--color-error-container)',
        'tertiary-dim': 'var(--color-tertiary-dim)',
        'primary-dim': 'var(--color-primary-dim)',
        'primary-fixed': 'var(--color-primary-fixed)',
        primary: 'var(--color-primary)',
        'on-primary': 'var(--color-on-primary)',
        tertiary: 'var(--color-tertiary)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        'inverse-primary': 'var(--color-inverse-primary)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'secondary-container': 'var(--color-secondary-container)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'on-error-container': 'var(--color-on-error-container)',
        'secondary-dim': 'var(--color-secondary-dim)',
        'primary-container': 'var(--color-primary-container)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        secondary: 'var(--color-secondary)',
        background: 'var(--color-background)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'on-secondary': 'var(--color-on-secondary)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        'inverse-surface': 'var(--color-inverse-surface)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        surface: 'var(--color-surface)',
        'surface-variant': 'var(--color-surface-variant)',
        'surface-container': 'var(--color-surface-container)',
        'surface-bright': 'var(--color-surface-bright)',
        'on-error': 'var(--color-on-error)',
        'surface-tint': 'var(--color-surface-tint)',
        'on-background': 'var(--color-on-background)',
        'surface-dim': 'var(--color-surface-dim)',
        error: 'var(--color-error)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        outline: 'var(--color-outline)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'on-surface': 'var(--color-on-surface)',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.125rem', // Changed from 0.25rem in original? No, original had lg: '0.25rem'
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Newsreader'],
        body: ['Manrope'],
        label: ['Manrope'],
        serif: ['Newsreader', 'serif'],
        sans: ['Manrope', 'sans-serif'],
      },
      backgroundImage: {
        'primary-gradient': 'linear-gradient(135deg, var(--color-primary) 0%, var(--color-primary-dim) 100%)',
      },
    },
  },
  plugins: [],
} satisfies Config

