import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: [
    './app/**/*.{vue,js,ts}',
    './components/**/*.{vue,js,ts}',
    './layouts/**/*.{vue,js,ts}',
    './composables/**/*.{vue,js,ts}',
    './stores/**/*.{vue,js,ts}',
    './tests/**/*.{vue,js,ts}',
  ],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#424855',
        'error-dim': '#d73357',
        'surface-container-high': '#18202f',
        'on-secondary-fixed-variant': '#6b369a',
        'on-tertiary': '#6a0a31',
        'error-container': '#a70138',
        'tertiary-dim': '#f17799',
        'primary-dim': '#8a4cfc',
        'primary-fixed': '#b28cff',
        primary: '#bd9dff',
        'on-primary': '#3c0089',
        tertiary: '#ff97b2',
        'on-tertiary-container': '#5a0027',
        'inverse-primary': '#742fe5',
        'on-secondary-fixed': '#4d137b',
        'on-primary-fixed-variant': '#390083',
        'primary-fixed-dim': '#a67aff',
        'secondary-container': '#612b8f',
        'on-secondary-container': '#e5c4ff',
        'on-error-container': '#ffb2b9',
        'secondary-dim': '#be86ef',
        'primary-container': '#b28cff',
        'secondary-fixed-dim': '#ddb3ff',
        secondary: '#c38bf5',
        background: '#080e1a',
        'secondary-fixed': '#e6c5ff',
        'on-secondary': '#3b0065',
        'on-primary-fixed': '#000000',
        'tertiary-container': '#fe81a4',
        'inverse-on-surface': '#4f5563',
        'inverse-surface': '#f9f9ff',
        'tertiary-fixed': '#ff8eac',
        surface: '#080e1a',
        'surface-variant': '#1e2637',
        'surface-container': '#131a28',
        'surface-bright': '#232c3e',
        'on-error': '#490013',
        'surface-tint': '#bd9dff',
        'on-background': '#e0e5f6',
        'surface-dim': '#080e1a',
        error: '#ff6e84',
        'surface-container-lowest': '#000000',
        'on-surface-variant': '#a6abbb',
        outline: '#707584',
        'tertiary-fixed-dim': '#f77c9e',
        'surface-container-low': '#0d1320',
        'surface-container-highest': '#1e2637',
        'on-tertiary-fixed-variant': '#711036',
        'on-tertiary-fixed': '#380016',
        'on-primary-container': '#2e006c',
        'on-surface': '#e0e5f6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Newsreader'],
        body: ['Manrope'],
        label: ['Manrope'],
      },
    },
  },
  plugins: [],
} satisfies Config
