// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import fs from "fs";
import os from "os";
import path from "path";
import Database from "better-sqlite3";
import { defineConfig } from "prisma/config";

const libraryPath = process.env.CALIBRE_LIBRARY_PATH;
const rawUrl = process.env["PRISMA_DATABASE_URL"] ?? process.env["DATABASE_URL"] ?? (libraryPath ? `file:${path.join(libraryPath, 'metadata.db')}` : undefined);

function sanitizeSqliteUrl(url?: string): string | undefined {
  if (!url || !url.startsWith("file:")) {
    return url;
  }

  const sqlitePath = url.replace(/^file:/, "");
  if (!fs.existsSync(sqlitePath)) {
    return url;
  }

  const tmpDir = path.join(os.tmpdir(), "librarian-prisma");
  fs.mkdirSync(tmpDir, { recursive: true });

  const tempFile = path.join(
    tmpDir,
    `metadata-prisma-${path.basename(sqlitePath)}-${process.pid}-${Date.now()}.db`,
  );
  fs.copyFileSync(sqlitePath, tempFile);

  const db = new Database(tempFile);
  try {
    const views = db.prepare("SELECT name FROM sqlite_master WHERE type='view'").all() as Array<{ name: string }>;
    for (const row of views) {
      db.prepare(`DROP VIEW IF EXISTS \"${row.name}\"`).run();
    }
  } finally {
    db.close();
  }

  return `file:${tempFile}`;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: sanitizeSqliteUrl(rawUrl),
  },
});
